version: "3.4"

services:
  ui:
    build:
      context: .
      target: runner_ui
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ui_vactory_https.loadbalancer.server.port=8080"
      - "traefik.http.routers.ui_vactory_https.rule=Host(`ui.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.api_tpui_vactory_httpse_phppgadmin_https.entrypoints=https"
      - "traefik.http.routers.ui_vactory_https.tls=true"

  docs:
    build:
      context: .
      target: runner_docs
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.docs_vactory_https.loadbalancer.server.port=8080"
      - "traefik.http.routers.docs_vactory_https.rule=Host(`docs.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.docs_vactory_https.entrypoints=https"
      - "traefik.http.routers.docs_vactory_https.tls=true"

networks:
  internal:
    external: true
