version: "3.4"

services:
  nextjs:
    build:
      context: .
      target: runner_app
      args:
        - NEXT_PUBLIC_DRUPAL_BASE_URL=${NEXT_PUBLIC_DRUPAL_BASE_URL}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_IMAGE_DOMAIN=${NEXT_IMAGE_DOMAIN}
        - DRUPAL_SITE_ID=${DRUPAL_SITE_ID}
        - DRUPAL_CLIENT_ID=${DRUPAL_CLIENT_ID}
        - DRUPAL_CLIENT_SECRET=${DRUPAL_CLIENT_SECRET}
        - DRUPAL_PREVIEW_SECRET=${DRUPAL_PREVIEW_SECRET}
        - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
        - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - JWT_SIGNING_PRIVATE_KEY=${JWT_SIGNING_PRIVATE_KEY}
        - SENTRY_DSN=${SENTRY_DSN}
        - NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=${NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID}
        - NEXT_PUBLIC_RECAPTCHA_SITEKEY=${NEXT_PUBLIC_RECAPTCHA_SITEKEY}
        - RECAPTCHA_SECRETKEY=${RECAPTCHA_SECRETKEY}
        - KEYCLOAK_ID=${KEYCLOAK_ID}
        - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
        - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vactory_http.rule=Host(`vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.vactory_http.entrypoints=http"
      - "traefik.http.routers.vactory_https.rule=Host(`vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.vactory_https.entrypoints=https"
      - "traefik.http.routers.vactory_https.tls=true"
      - "traefik.http.routers.vactory_https.tls.certresolver=k8spreprodchallenge"

  ui:
    build:
      context: .
      target: runner_ui
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui_vactory_http.rule=Host(`ui.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.ui_vactory_http.entrypoints=http"
      - "traefik.http.routers.ui_vactory_https.rule=Host(`ui.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.ui_vactory_https.entrypoints=https"
      - "traefik.http.routers.ui_vactory_https.tls=true"
      - "traefik.http.routers.ui_vactory_https.tls.certresolver=k8spreprodchallenge"

  docs:
    build:
      context: .
      target: runner_docs
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs_vactory_http.rule=Host(`docs.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.docs_vactory_http.entrypoints=http"
      - "traefik.http.routers.docs_vactory_https.rule=Host(`docs.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.docs_vactory_https.entrypoints=https"
      - "traefik.http.routers.docs_vactory_https.tls=true"
      - "traefik.http.routers.docs_vactory_https.tls.certresolver=k8spreprodchallenge"

networks:
  internal:
    external: true
