version: "3.4"

services:
  ui:
    build:
      context: .
      target: runner_ui
    restart: unless-stopped
    ports:
      - "8081:8080"

  docs:
    build:
      context: .
      target: runner_docs
    restart: unless-stopped
    ports:
      - "8082:8080"
