version: "3.4"

services:
  nextjs:
    build:
      context: .
      target: runner_app
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.vactory_http.rule=Host(`vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.vactory_http.entrypoints=http"
      - "traefik.http.routers.vactory_https.rule=Host(`vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.vactory_https.entrypoints=https"
      - "traefik.http.routers.vactory_https.tls=true"
      - "traefik.http.routers.vactory_https.tls.certresolver=k8spreprodchallenge"

  ui:
    build:
      context: .
      target: runner_ui
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui_vactory_http.rule=Host(`ui.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.ui_vactory_http.entrypoints=http"
      - "traefik.http.routers.ui_vactory_https.rule=Host(`ui.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.ui_vactory_https.entrypoints=https"
      - "traefik.http.routers.ui_vactory_https.tls=true"
      - "traefik.http.routers.ui_vactory_https.tls.certresolver=k8spreprodchallenge"

  docs:
    build:
      context: .
      target: runner_docs
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs_vactory_http.rule=Host(`docs.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.docs_vactory_http.entrypoints=http"
      - "traefik.http.routers.docs_vactory_https.rule=Host(`docs.vactory.k8s.lapreprod.com`)"
      - "traefik.http.routers.docs_vactory_https.entrypoints=https"
      - "traefik.http.routers.docs_vactory_https.tls=true"
      - "traefik.http.routers.docs_vactory_https.tls.certresolver=k8spreprodchallenge"

networks:
  internal:
    external: true
